### ISSUE TITLE
How do I use after cloning the repo ?

### ISSUE THREAD

**Issue by Sowgandh1991** [Johni0702/libopus.js#2]
Hi I cloned the repo but I am not able to locate 'liboopus.js' file within the build folder. How do i use this package ?

**Comment by Johni0702** [comment]
The pre-built lib is only part of the npm package. So, if you `npm install libopus.js` you'll find it at `node-modules/libopus.js/build/libopus.js`.

If you're cloning the repo via git, you'll have to [build it yourself](https://github.com/Johni0702/libopus.js#building-from-source), after which you'll find it at `build/libopus.js`.
